In [81]:
# Week 1

from math import log2
import numpy as np
import matplotlib.pyplot as plt
from contextlib import suppress

def infocontent(p):
    return - log2(p)

def entropy1(p: np.array):
    if type(p) == list:
        p = np.array(p)
    if np.sum(p) != 1:
        raise Exception('The sum of the elements of p should be = 1: {}'.format(p))
    with suppress(ZeroDivisionError):
        H = - np.dot(p, np.where(p > 0, np.log2(p), 0))

    return  H


In [82]:
#from week1 import infocontent, entropy
import matplotlib.pyplot as plt
import numpy as np

infocontent(1/24)

4.584962500721156

In [83]:
# Calculate entropy of a sequence of stuff

import collections
 
from scipy.stats import entropy
  
def calculateDatasetShannonEntropy(items):
    itemscount = collections.Counter(items)
    
    # probability = # item x / # total number of items
    dist = [x/sum(itemscount.values()) for x in itemscount.values()]
 
    # use scipy to calculate entropy
    entropy_value = entropy(dist, base=2)
 
    return entropy_value

In [97]:
def jointentropy(p: np.array):
    print(type(p))
    print(p.shape[0])
    print(p.shape[1])
    if type(p) == list:
        p = np.array(p)
    if p.shape[0] != p.shape[1]:
        raise Exception("p must be a square matrix")
    print("np.sum(p, axis=0) != 1 :", np.sum(p, axis=0) != 1)
    print("np.sum(p, axis=0):", np.sum(p, axis=0))
    if ( np.sum(p, axis=0) != 1).any() or (np.sum(p, axis=1) != 1).any():
        raise Exception('The sum of the elements of p should be = 1 in all dimensions {}'.format(p))
    with suppress(ZeroDivisionError):
        H = - np.dot(p, np.where(p > 0, np.log2(p), 0))
        H = np.sum(H)

    return  H

In [100]:
a = np.array([[0.1, 0.9], [0.9, 0.1]])
print(a.shape)
je=jointentropy(a)
print("Joint entropy ", je)

(2, 2)
<class 'numpy.ndarray'>
2
2
np.sum(p, axis=0) != 1 : [False False]
np.sum(p, axis=0): [1. 1.]
Joint entropy  6.947862376664824


Exception: The sum of the elements of p should be = 1: [0.1 0.9 0.9 0.1]

In [92]:
print("Join entropy with scipy:",  entropy(a.ravel(), base=2))
#entropy(p.ravel(), base=2)

Join entropy with scipy: 1.580000754875826


In [4]:
entropy(np.array([0.1, 0.9]))

0.4689955935892812

In [1]:
# Plot H(X) as a function of p(x=1) for binary X

x1=np.linspace(0, 1, num=51)
x2 = 1 - x1
x2


x = np.array(list(zip(x1,x2)))
x

plt.plot(x1, [ entropy(xi) for xi in x])

NameError: name 'np' is not defined

In [6]:
# test entropy
entropy([0.25, 0.25, 0.25, 0.25])

2.0

In [7]:
# 5. Coming back to the characters that we could play Guess Who? with on the Kooky characters sheet 
# (Links to an external site.), validate that (using your entropy function if you need to)

# (1) H(who) entropy of the characters identity - Question: who is your character? 
entropy([1/24 for i in range(24)])

4.584962500721155

In [8]:
# (2) H(one eye question) - Question : Does your character has one eye
entropy([5/24, 19/24])

0.7382848661434506

In [9]:
# (3) H(Jason question) - - Question : Is your character Jason
entropy(np.array([1/24, 23/24]))

0.24988229283318544

In [10]:
# entropy([0, 0.5, 0.5])
# https://stackoverflow.com/questions/21752989/numpy-efficiently-avoid-0s-when-taking-logmatrix
# https://www.w3schools.com/python/numpy/numpy_ufunc_logs.asp
# https://stackoverflow.com/questions/15450192/fastest-way-to-compute-entropy-in-python

p = np.array([0.1, 0.4, 0.5])
- np.dot(p, np.where(p > 0, np.log2(p), 0))

1.360964047443681

In [11]:
from scipy.stats import entropy
p = np.array([0, 0.5, 0.5])
entropy(p, base=2)

1.0

In [13]:
p = np.array([0.5, 0.5])
entropy(p, base=2)

1.0

In [14]:
p = np.array([0.2, 0.30, 0.25, 0.25])
entropy(p, base=2)

1.9854752972273346

In [45]:
# Plot H(X) as a function of p(x=1) for X with alphabet C
# P(p(x=a), p(x=b), p(x=c), p(x=d))

x=np.linspace(0, 1, num=51)
x=x.reshape(51,1)

def makexx(x):

    print("np.cumsum: ", np.cumsum(x, axis=1))
    print("np.cumsum.shape", np.cumsum(x, axis=1).shape)
    x2 = np.ones((51,1)) - np.cumsum(x, axis=1)
    print("x2.shape:", x2.shape)
    x = np.concatenate((x, x2), axis=1)
    print(x)
    print(x.shape)
    return x


first time
np.cumsum:  [[0.  ]
 [0.02]
 [0.04]
 [0.06]
 [0.08]
 [0.1 ]
 [0.12]
 [0.14]
 [0.16]
 [0.18]
 [0.2 ]
 [0.22]
 [0.24]
 [0.26]
 [0.28]
 [0.3 ]
 [0.32]
 [0.34]
 [0.36]
 [0.38]
 [0.4 ]
 [0.42]
 [0.44]
 [0.46]
 [0.48]
 [0.5 ]
 [0.52]
 [0.54]
 [0.56]
 [0.58]
 [0.6 ]
 [0.62]
 [0.64]
 [0.66]
 [0.68]
 [0.7 ]
 [0.72]
 [0.74]
 [0.76]
 [0.78]
 [0.8 ]
 [0.82]
 [0.84]
 [0.86]
 [0.88]
 [0.9 ]
 [0.92]
 [0.94]
 [0.96]
 [0.98]
 [1.  ]]
np.cumsum.shape (51, 1)
x2.shape: (51, 1)
[[0.   1.  ]
 [0.02 0.98]
 [0.04 0.96]
 [0.06 0.94]
 [0.08 0.92]
 [0.1  0.9 ]
 [0.12 0.88]
 [0.14 0.86]
 [0.16 0.84]
 [0.18 0.82]
 [0.2  0.8 ]
 [0.22 0.78]
 [0.24 0.76]
 [0.26 0.74]
 [0.28 0.72]
 [0.3  0.7 ]
 [0.32 0.68]
 [0.34 0.66]
 [0.36 0.64]
 [0.38 0.62]
 [0.4  0.6 ]
 [0.42 0.58]
 [0.44 0.56]
 [0.46 0.54]
 [0.48 0.52]
 [0.5  0.5 ]
 [0.52 0.48]
 [0.54 0.46]
 [0.56 0.44]
 [0.58 0.42]
 [0.6  0.4 ]
 [0.62 0.38]
 [0.64 0.36]
 [0.66 0.34]
 [0.68 0.32]
 [0.7  0.3 ]
 [0.72 0.28]
 [0.74 0.26]
 [0.76 0.24]
 [0.78 0.22]
 [0.8 

In [ ]:
# Plot H(X) as a function of p(x=1) for X with alphabet C
# P(p(x1=1), p(x2=2), p(x3=3), p(x4=4))

In [47]:
# Calculate entropy of a sequence of stuff

import collections
 
from scipy.stats import entropy
  
def calculateDatasetShannonEntropy(items):
    itemscount = collections.Counter(items)
    
    # probability = # item x / # total number of items
    dist = [x/sum(itemscount.values()) for x in itemscount.values()]
 
    # use scipy to calculate entropy
    entropy_value = entropy(dist, base=2)
 
    return entropy_value

calculateDatasetShannonEntropy(['hello', 'bye', 'bye'])

0.9182958340544894

In [48]:
calculateDatasetShannonEntropy(['bye', 'bye', 'bye'])

0.0

In [50]:
calculateDatasetShannonEntropy(['bye', 'hello', 'bye', 'hello'])

1.0

In [51]:
calculateDatasetShannonEntropy([1,1,1,1])

0.0

In [52]:
calculateDatasetShannonEntropy([0,1,0,1])

1.0

In [64]:
calculateDatasetShannonEntropy([0,1,1,2,2,0])

1.584962500721156

In [ ]:
calculateDatasetShannonEntropy(['bye', 'hello', 'bye', 'hello'])

In [88]:
#https://stackoverflow.com/questions/51022380/how-to-calculate-entropy-of-joint-distribution

In [2]:
        import numpy as np
        p = np.array([[0.125, 0.0625, 0.03125, 0.03125],
             [0.0625, 0.125, 0.03125, 0.03125],
             [0.0625, 0.0625, 0.0625, 0.0625],
             [0.25,0,0,0]])

In [3]:
print(p)

[[0.125   0.0625  0.03125 0.03125]
 [0.0625  0.125   0.03125 0.03125]
 [0.0625  0.0625  0.0625  0.0625 ]
 [0.25    0.      0.      0.     ]]


In [6]:
dim=0
pdim = np.sum(p, axis=dim)
print(pdim)

[0.5   0.25  0.125 0.125]


In [7]:
dim=1
pdim = np.sum(p, axis=dim)
print(pdim)

[0.25 0.25 0.25 0.25]


In [10]:
def marginalP(p: np.array, dim: int):
    return np.sum(p, axis=dim)

In [11]:
marginalX = lambda  p : marginalP(p, 0)

In [12]:
marginalX(p)

array([0.5  , 0.25 , 0.125, 0.125])

In [13]:
p.shape

(4, 4)

In [17]:
p.ndim

2

In [18]:
def marginalP(p: np.array, dim: int):
    if dim + 1 > p.ndim:
        raise Exception('The probability matrix has only {} dimensions while you are requesting to get marginal in dimension {}'.format(p.ndim, dim+1))
    return np.sum(p, axis=dim)

In [20]:
marginalP(p, 2)

Exception: The probability matrix has only 2 dimensions while you are requesting to get marginal in dimension 2

In [24]:
from week1 import entropy1, marginalX, marginalY
entropy1(marginalX(p))
# 1.75 is the correct answer (7/4 bits)

1.75

In [26]:
# H(Y) = 2 bits
entropy1(marginalY(p))

2.0

In [30]:
p.shape

(4, 4)

In [37]:
    for i in range(p.shape[0]):
        print(i)
        print(p)
        print(p[i])
        pyi = np.sum(p[i])
        print(pyi)

0
[[0.125   0.0625  0.03125 0.03125]
 [0.0625  0.125   0.03125 0.03125]
 [0.0625  0.0625  0.0625  0.0625 ]
 [0.25    0.      0.      0.     ]]
[0.125   0.0625  0.03125 0.03125]
0.25
1
[[0.125   0.0625  0.03125 0.03125]
 [0.0625  0.125   0.03125 0.03125]
 [0.0625  0.0625  0.0625  0.0625 ]
 [0.25    0.      0.      0.     ]]
[0.0625  0.125   0.03125 0.03125]
0.25
2
[[0.125   0.0625  0.03125 0.03125]
 [0.0625  0.125   0.03125 0.03125]
 [0.0625  0.0625  0.0625  0.0625 ]
 [0.25    0.      0.      0.     ]]
[0.0625 0.0625 0.0625 0.0625]
0.25
3
[[0.125   0.0625  0.03125 0.03125]
 [0.0625  0.125   0.03125 0.03125]
 [0.0625  0.0625  0.0625  0.0625 ]
 [0.25    0.      0.      0.     ]]
[0.25 0.   0.   0.  ]
0.25


In [38]:
def entropyXGivenY(p: np.array):
    # 2 dim only for now

    # e.g.
    # p(x,y)
    # Y rows (dim=0) \X   columns (dim=1)
    # p = np.array([[0.125, 0.0625, 0.03125, 0.03125],
    #       [0.0625, 0.125, 0.03125, 0.03125],
    #       [0.0625, 0.0625, 0.0625, 0.0625],
    #       [0.25,0,0,0]])
    # Correct answer = 11/8 = 1.375
    total = 0
    for i in range(p.shape[0]):
        pyi = np.sum(p[i])
        total+= pyi * entropy1(1/pyi * p[i])

    return total

In [39]:
entropyXGivenY(p)

/home/jovyan/notebooks/CSYS5030/week1.py:19: RuntimeWarning: divide by zero encountered in log2
  H = - np.dot(p, np.where(p > 0, np.log2(p), 0))


1.375

In [40]:
11/8

1.375